name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry
      shell: bash

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"
    
    - name: Configure Poetry to use official PyPI
      run: |
        poetry source remove 清华 || true
        poetry source remove 阿里云 || true  
        poetry source remove 豆瓣 || true
        poetry source add --priority=default pypi https://pypi.org/simple/
      shell: bash

    - run: poetry install
      shell: bash